### ISSUE TITLE
inner域名清理一下

### ISSUE THREAD

**Issue by 0c0c0f** [feikerwu/node-proxy-demo#1]
：）

**Comment by feikerwu** [comment]
感谢提醒，已清 🤫

**Comment by 0c0c0f** [comment]
还有这个哈
req.pipe(request("https://bggray-activity.bigo.tv" + originalUrl)).pipe(res);

**Comment by feikerwu** [comment]
。。 你这哪里找出来的，搜遍了commit都没找到。。
